from django.db import models

class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.IntegerField(null=True)
    reports_to = models.IntegerField(null=True)
    emp_code = models.IntegerField(null=True)
    comp_id = models.IntegerField(null=True)
    dept_id = models.IntegerField(null=True)
    desg_id = models.IntegerField(null=True)
    grade_id = models.IntegerField(null=True)
    emp_name = models.CharField(max_length=255,null=True)
    emp_img = models.TextField(null=True)
    emp_gender = models.CharField(max_length=10,null=True)
    emp_dob = models.DateField(null=True)
    curr_addr = models.TextField(null=True)
    perm_addr = models.TextField(null=True)
    blood_grp = models.CharField(max_length=5 ,null=True)
    alt_contact = models.CharField(max_length=15,null=True)
    email = models.CharField(max_length=30,null=True)
    driv_lic = models.CharField(max_length=255,null=True)
    aadhar_no = models.CharField(max_length=25,null=True)
    voter_id = models.CharField(max_length=50,null=True)
    pan_no = models.CharField(max_length=50,null=True)
    emp_type = models.IntegerField(null=True)
    emp_status = models.IntegerField(null=True)
    old_uan = models.CharField(max_length=50,null=True)
    curr_uan = models.CharField(max_length=50,null=True)
    old_pf = models.CharField(max_length=50,null=True)
    curr_pf = models.CharField(max_length=50,null=True)
    old_esi = models.CharField(max_length=50,null=True)
    curr_esi = models.CharField(max_length=50,null=True)
    join_dt = models.DateField(null=True)
    leave_dt = models.DateField(null=True)
    active = models.IntegerField(null=True)
    leave_allotted = models.IntegerField(null=True)
    deleted_at = models.DateTimeField(null=True)
