from django.db import models

class LeaveTypeModel(models.Model):
	id = models.AutoField(primary_key = True)
	name = models.CharField(max_length = 255 ,null=True)
	leave_per_year = models.CharField(max_length = 255 , null=True)
	total =  models.CharField(max_length = 255 , null=True)
	generate_days =  models.CharField(max_length = 255 , null=True)
	max_apply_once = models.CharField(max_length = 255 , null=True)
	min_apply_once = models.CharField(max_length = 255 , null=True)
	max_days_month = models.CharField(max_length = 255 , null=True)
	max_apply_month = models.CharField(max_length = 255 , null=True)
	max_apply_year = models.CharField(max_length = 255 , null=True)
	without_pay = models.CharField(max_length = 255 , null=True)
	dont_show = models.CharField(max_length = 255 , null=True)
	carry_forward = models.CharField(max_length = 255 ,null=True)
	docs_required = models.CharField(max_length = 255 ,null=True)
	without_pay = models.CharField(max_length = 255 ,null=True)
	dont_show = models.CharField(max_length = 255 ,null=True)
	def __str__(self):
		return self.name

class LeaveAllotment(models.Model):
	id = models.AutoField(primary_key = True )	
	leave_mast_id = models.ForeignKey(LeaveTypeModel, on_delete=models.CASCADE)	
	user_id = models.ForeignKey('employee.User', on_delete=models.CASCADE)	
	status = models.BooleanField(null=True)	
	start_date = models.DateField(null=True)	
	end_date = models.DateField(null=True)	
	inital_bal = models.CharField(max_length = 255 ,null=True)	
	current_bal = models.CharField(max_length = 255,null=True)	
	generated_at = models.DateField(null=True)	

class LeaveApply(models.Model):
	id = models.AutoField(primary_key = True)
	reports_to = models.ForeignKey('employee.User',related_name='report_user', null=True, on_delete=models.SET_NULL)
	leave_type_id = models.ForeignKey('leavemanagement.LeaveTypeModel', null=True, on_delete=models.SET_NULL)
	day_status = models.CharField(max_length = 255, null = True)
	date_from = models.DateField(null = True)
	date_to = models.DateField(null = True)
	count = models.IntegerField(null =True)
	reason = models.TextField(null =True)
	file_path = models.CharField(max_length = 255, null =True)
	addr_during_leave = models.IntegerField(null = True)
	contact_no = models.CharField(max_length = 255, null = True)
	approver = models.ForeignKey('employee.User',related_name='person2persons', null=True, on_delete=models.SET_NULL)
	status = models.BooleanField(null = True)
	applicant_remark = models.TextField(null =True)
	approver_remark = models.TextField(null =True)
	hr_remark = models.TextField(null =True)
	deleted_at = models.DateField(null = True)
	carry_count = models.IntegerField(null = True)
	paid_count = models.IntegerField(null = True)
	unpaid_count = models.IntegerField(null = True)
	user =  models.ForeignKey('employee.User', null=True,related_name='user', on_delete=models.SET_NULL)
	subadmin_approval = models.CharField(max_length = 50, null = True)
	admin_approval = models.CharField(null = True,max_length=50)
	teamlead_approval = models.CharField(null = True,max_length=50)	
