# Generated by Django 2.2.6 on 2020-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reports_to', models.IntegerField()),
                ('emp_code', models.IntegerField()),
                ('comp_id', models.IntegerField()),
                ('dept_id', models.IntegerField()),
                ('desg_id', models.IntegerField()),
                ('grade_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_img', models.TextField()),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_dob', models.DateField()),
                ('curr_addr', models.TextField()),
                ('perm_addr', models.TextField()),
                ('blood_grp', models.CharField(max_length=5)),
                ('alt_contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('driv_lic', models.CharField(max_length=255)),
                ('aadhar_no', models.CharField(max_length=25)),
                ('voter_id', models.CharField(max_length=50)),
                ('pan_no', models.CharField(max_length=50)),
                ('emp_type', models.IntegerField()),
                ('emp_status', models.IntegerField()),
                ('old_uan', models.CharField(max_length=50)),
                ('curr_uan', models.CharField(max_length=50)),
                ('old_pf', models.CharField(max_length=50)),
                ('curr_pf', models.CharField(max_length=50)),
                ('old_esi', models.CharField(max_length=50)),
                ('curr_esi', models.CharField(max_length=50)),
                ('join_dt', models.DateField()),
                ('leave_dt', models.DateField()),
                ('active', models.IntegerField()),
                ('leave_allotted', models.IntegerField()),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
