# Generated by Django 2.2.6 on 2020-01-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
