# Generated by Django 2.2 on 2020-02-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_auto_20200220_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='grade_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.EmployeeGrade'),
        ),
    ]
