# Generated by Django 2.2 on 2020-02-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0003_auto_20200220_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.DepartmentModel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desg_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.DesignationModel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.EmployeeType'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.EmployeeStatus'),
        ),
    ]
