# Generated by Django 2.2 on 2020-02-20 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leavemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypemodel',
            name='carry_forward',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='docs_required',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='dont_show',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='generate_days',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='max_apply_month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='max_apply_once',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='max_apply_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='max_days_month',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='min_apply_once',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='total',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leavetypemodel',
            name='without_pay',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leavetypemodel',
            name='leave_per_year',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LeaveAllotment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('inital_bal', models.CharField(max_length=255, null=True)),
                ('current_bal', models.CharField(max_length=255, null=True)),
                ('generated_at', models.DateField(null=True)),
                ('leave_mast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leavemanagement.LeaveTypeModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
