# Generated by Django 2.2 on 2020-02-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0003_leaveapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='reports_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
