# Generated by Django 2.2 on 2020-02-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemanagement', '0004_auto_20200225_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='admin_approval',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='subadmin_approval',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapply',
            name='teamlead_approval',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
